### ISSUE TITLE
Source segments text display changes when moving cursor

### ISSUE THREAD

**Issue by afduggirala** [npizzigati/Vimish#1]
Hello Nick,
I am observing that when I move around some target text, the line display of some of the text in source segments is changing. This means the current position of the line I am editing on the screen changes as well, which is bothersome.
You can observe the behavior in this video, https://user.fm/files/v2-ea4ba7558baf351769bde6a57e0540a6/OmegaT%205.7.1%20__%20FSIS%202022-11-25%2010-18-05.mp4
I believe this does not happen when not using the plugin. I suspect this has to do with the way the cursor is displayed when using the plugin. 

Thanks a lot,

**Comment by npizzigati** [comment]
Hey Anil,
I'm having trouble replicating this. Can you tell me the following:
1. Editor font you're using and size.
2. Platform (Windows, Mac or Linux).
3. Whether you saw this same problem in the earlier versions of the plugin.
4. Whether you experience the same problem with other source files.

Thanks!

**Comment by afduggirala** [comment]
Hello Nick,
Your answers:

1. Dialog 13. Default I guess.
2. On Windoze, for now. I am using w/JRE, but am using the Adoptium jre, https://adoptium.net/temurin/releases/?version=11
3. I just tried reverting back to v. 1.2 and the problem persists.
4. I am experiencing the same problem with other source files. Obviously, ones that are more than one line long.

I am sure you have noticed (know about) the change in the shape of the cursor when going from one character to another. So the cursor is much thinner over an "i" character than it is over a "w" character. The mysterious source segment changes happen when one goes from one cursor thickness to a different one. However, from the video I sent before you notice that the visual changes don't just happen on the active source segment, but on other ones as well.

thank you,

**Comment by npizzigati** [comment]
Thanks for the info -- I was able to reproduce the issue today. I don't have an immediate fix, but hopefully I'll be able to come up with one sooner rather than later. 

One imperfect workaround at this point is to use a monospace font, like Lucida console. The issue will still exist, but you will only see it when you change from insert to normal mode (or vice-versa).

**Comment by npizzigati** [comment]
Hi Anil,
I think I've got this fixed. Could you try the [latest version](https://github.com/npizzigati/Vimish/releases/download/v0.2.3/Vimish-0.2.3.jar) and let me know if you still experience any issues?

**Comment by npizzigati** [comment]
Hi Anil- I'm going to go ahead and close this issue as fixed. If you still experience it, just let me know and I'll reopen it.
