### ISSUE TITLE
Cannot insert glossary match

### ISSUE THREAD

**Issue by GregoryVigoTorres** [npizzigati/Vimish#2]
When a glossary match appears in the popup below the current segment I cannot insert the match when I press ENTER.
Without the plugin ENTER inserts the glossary match.
And the arrow keys won't let me choose from multiple glossary matches.
The status bar shows a use tab to advance is activated message.
I don't code much in Java, but it looks like in Actions.executeEnter the only actions handled are go to next segment, or not.

**Comment by npizzigati** [comment]
Thanks for reporting the issue. It should now be fixed. Please try the [latest release](https://github.com/npizzigati/Vimish/releases/download/v0.2.1/Vimish-0.2.1.jar).

**Comment by npizzigati** [comment]
There were a couple issues with the previous fix. This [new release](https://github.com/npizzigati/Vimish/releases/download/v0.2.2/Vimish-0.2.2.jar) should fix them.
