### ISSUE TITLE
Not working with OmegaT 6.1.0

### ISSUE THREAD

**Issue by equipematou** [npizzigati/Vimish#6]
Hi Nick, 

I have vimish 0.2.4; it works with 6.0.

When I start 6.1.0 with the vimish plugin installed I cannot translate segments. Trying the various vi keys to enter text it does not respond. If I move the vimish plugin out of the plugins directory I can work normally.

Can you verify that it does not work with 6.1.0, or suggest things I might try if you know it works? Thanks!

**Comment by npizzigati** [comment]
Hi Michael-

Thanks a million for discovering this issue! The problem should be fixed now, in [v0.2.5](https://github.com/npizzigati/Vimish/releases/download/v0.2.5/Vimish-0.2.5.jar). Please let me know if you continue to experience any weirdness.

**Comment by equipematou** [comment]
It worked in a quick test just now, if I find anything else I will let you know. Thanks much for fixing it!

**Comment by npizzigati** [comment]
Great! I will close this issue, but of course feel free to open another one if problems persist.
